export const tabs = [
  'Dashboard',
  'Solicitudes',
  'Cotizaciones',
  'Catalogo',
  'Asesores',
  'Clientes',
  'Eventos',
  'Inventario',
  'Reportes',
]

export const eventsSeed = [
  {
    id: 'EV-001',
    title: 'Boda de Maria Gonzalez',
    client: 'Maria Gonzalez',
    kind: 'boda',
    status: 'confirmado',
    date: '2024-01-22',
    hour: '18:00',
    place: 'Jardin los Rosales, Bogota',
    advisor: 'Carlos Ruiz',
    total: 12000,
    advance: 6000,
    pending: 6000,
    services: ['Decoracion', 'Sonido', 'Mobiliario', 'Catering'],
    note: 'Cliente VIP, atencion especial en decoracion floral',
  },
  {
    id: 'EV-002',
    title: 'Evento corporativo TechCorp',
    client: 'TechCorp',
    kind: 'corporativo',
    status: 'pendiente_pago',
    date: '2024-01-24',
    hour: '19:00',
    place: 'Hotel Grand Plaza',
    advisor: 'Laura Rojas',
    total: 18000,
    advance: 7000,
    pending: 11000,
    services: ['Tarima', 'Pantallas', 'Iluminacion'],
    note: 'Pendiente de aprobacion final del presupuesto.',
  },
]

export const inventorySeed = [
  {
    id: 'IT-001',
    name: 'Castillo Inflable Grande',
    category: 'Inflables',
    status: 'bueno',
    stock: 3,
    total: 5,
    price: 150,
    location: 'Bodega A-1',
    updatedAt: '2024-01-05',
    description: 'Castillo inflable de 6x5 metros para 15 ninos',
  },
  {
    id: 'IT-002',
    name: 'Mesa Redonda (10 personas)',
    category: 'Mobiliario',
    status: 'bueno',
    stock: 18,
    total: 20,
    price: 25,
    location: 'Bodega B-2',
    updatedAt: '2023-12-15',
    description: 'Mesa redonda blanca para eventos',
  },
  {
    id: 'IT-003',
    name: 'Sistema de Sonido Profesional',
    category: 'Audiovisual',
    status: 'excelente',
    stock: 2,
    total: 3,
    price: 400,
    location: 'Bodega C-1',
    updatedAt: '2024-01-10',
    description: 'Sistema completo con microfonos y amplificadores',
  },
  {
    id: 'IT-004',
    name: 'Proyector HD',
    category: 'Audiovisual',
    status: 'mantenimiento',
    stock: 1,
    total: 2,
    price: 200,
    location: 'Taller',
    updatedAt: '2024-01-12',
    description: 'Proyector 1080p con entrada HDMI',
  },
  {
    id: 'IT-005',
    name: 'Silla Tiffany Blanca',
    category: 'Mobiliario',
    status: 'bueno',
    stock: 80,
    total: 100,
    price: 8,
    location: 'Bodega B-1',
    updatedAt: '2024-01-03',
    description: 'Silla tiffany blanca para eventos sociales',
  },
]

export const currency = (n) => `$${new Intl.NumberFormat('es-CO').format(n)}`
